server:
  port: 8080
  servlet:
    context-path: /api

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # if using Hibernate as JPA provider
    show-sql: true # set to true for debugging purposes

logging:
  level:
    org.springframework: INFO # set logging level for Spring Framework
